# Usa uma imagem base do Java (ajuste a versão conforme necessário)
FROM openjdk:17-jdk-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o arquivo JAR da aplicação para o contêiner
COPY target/tome-of-heroes-0.0.1-SNAPSHOT.jar app.jar

# Expõe a porta que a aplicação vai rodar 
EXPOSE 8080

# Comando para rodar a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]